/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pi02;

import data.Compras;
import data.ProdutosDAO;
import static java.lang.Float.parseFloat;
import javax.swing.JOptionPane;

/**
 *
 * @author ggr12
 */
public class AdicionarCompra extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarCompra
     */
    public AdicionarCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdicionarCompra = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        lblAdicionarCompraTitulo = new javax.swing.JLabel();
        lblDataCompra = new javax.swing.JLabel();
        txtDataCompra = new javax.swing.JTextField();
        lblValorTotal = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        lblFormPag = new javax.swing.JLabel();
        txtFormPag = new javax.swing.JTextField();
        btnIniciarAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAdicionarCompra.setBackground(new java.awt.Color(51, 51, 51));

        btnVoltar.setBackground(new java.awt.Color(102, 102, 102));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblAdicionarCompraTitulo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblAdicionarCompraTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblAdicionarCompraTitulo.setText("Adicionar compra");

        lblDataCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblDataCompra.setText("Data da compra:");

        txtDataCompra.setToolTipText("Formato aaaa-mm-dd");

        lblValorTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblValorTotal.setText("Valor total da compra:");

        txtValorTotal.setToolTipText("");

        lblFormPag.setForeground(new java.awt.Color(255, 255, 255));
        lblFormPag.setText("Forma de pagamento:");

        txtFormPag.setToolTipText("");

        btnIniciarAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnIniciarAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIniciarAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciarAdd.setText("Iniciar adição de produtos");
        btnIniciarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdicionarCompraLayout = new javax.swing.GroupLayout(pnlAdicionarCompra);
        pnlAdicionarCompra.setLayout(pnlAdicionarCompraLayout);
        pnlAdicionarCompraLayout.setHorizontalGroup(
            pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicionarCompraLayout.createSequentialGroup()
                .addGroup(pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdicionarCompraLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdicionarCompraTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAdicionarCompraLayout.createSequentialGroup()
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIniciarAdd))))
                    .addGroup(pnlAdicionarCompraLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAdicionarCompraLayout.createSequentialGroup()
                                .addComponent(lblFormPag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFormPag, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdicionarCompraLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValorTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlAdicionarCompraLayout.setVerticalGroup(
            pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicionarCompraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAdicionarCompraTitulo)
                .addGap(18, 18, 18)
                .addGroup(pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataCompra)
                    .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotal)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormPag)
                    .addComponent(txtFormPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAdicionarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        txtDataCompra.getAccessibleContext().setAccessibleName("Formato dd/mm/aaaa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdicionarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdicionarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarAddActionPerformed
       Compras compra = new Compras();
       ProdutosDAO dao = new ProdutosDAO();
       boolean status;
       int resposta;
       
       compra.setDataMercado(txtDataCompra.getText());
       compra.setValorTotal(parseFloat(txtValorTotal.getText()));
       compra.setFormaPagamento(txtFormPag.getText());
              
       dao = new ProdutosDAO();
       
       status = dao.conectar();
       if(status == false){
                JOptionPane.showMessageDialog(null,"Erro de conexão!");
            }else{
                resposta = dao.cadastrarCompra(compra);
                if(resposta == 1){
                    JOptionPane.showMessageDialog(null,"Dados incluídos com sucesso!");
                    AdicionarProduto telaAdicionarProduto = new AdicionarProduto();
                    telaAdicionarProduto.setVisible(true);
                } else if (resposta == 1062){
                    JOptionPane.showMessageDialog(null,"Compra já foi cadastrado!");   
                }else{
                    JOptionPane.showMessageDialog(null,"Erro ao tentar inserir dados!");
                }
                dao.desconectar();
        }
    }//GEN-LAST:event_btnIniciarAddActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarAdd;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblAdicionarCompraTitulo;
    private javax.swing.JLabel lblDataCompra;
    private javax.swing.JLabel lblFormPag;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnlAdicionarCompra;
    private javax.swing.JTextField txtDataCompra;
    private javax.swing.JTextField txtFormPag;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
