/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pi02;

import data.Compras;
import data.Produtos;
import data.ProdutosDAO;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author ggr12
 */
public class AdicionarProduto extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarProduto
     */
    public AdicionarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdicionarProduto = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        lblAdicionarProdutoTitulo = new javax.swing.JLabel();
        lblNomeProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lblNomeMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblPrecoProd = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        btnConcluirAdd = new javax.swing.JButton();
        lblQuant = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        pnlUltimoProduto = new javax.swing.JPanel();
        lblUltimoProduto = new javax.swing.JLabel();
        lblUltimoProdutoNome = new javax.swing.JLabel();
        lblUltimoProdutoMarca = new javax.swing.JLabel();
        lblUltimoProdutoPreco = new javax.swing.JLabel();
        lblUltimoProdutoQuantidade = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAdicionarProduto.setBackground(new java.awt.Color(51, 51, 51));

        btnVoltar.setBackground(new java.awt.Color(102, 102, 102));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblAdicionarProdutoTitulo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblAdicionarProdutoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblAdicionarProdutoTitulo.setText("Adicionar produtos");

        lblNomeProduto.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeProduto.setText("Nome do produto:");

        txtProduto.setToolTipText("");

        lblNomeMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeMarca.setText("Marca:");

        txtMarca.setToolTipText("");

        lblPrecoProd.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecoProd.setText("Preço:");

        txtPreco.setToolTipText("");

        btnConcluirAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnConcluirAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnConcluirAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnConcluirAdd.setText("Concluir adição");
        btnConcluirAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirAddActionPerformed(evt);
            }
        });

        lblQuant.setForeground(new java.awt.Color(255, 255, 255));
        lblQuant.setText("Quantidade:");

        txtQuantidade.setToolTipText("");

        pnlUltimoProduto.setBackground(new java.awt.Color(51, 51, 51));

        lblUltimoProduto.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblUltimoProduto.setForeground(new java.awt.Color(255, 255, 255));
        lblUltimoProduto.setText("Último produto adicionado");

        lblUltimoProdutoNome.setForeground(new java.awt.Color(255, 255, 255));
        lblUltimoProdutoNome.setText("Produto: ");

        lblUltimoProdutoMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblUltimoProdutoMarca.setText("Marca:");

        lblUltimoProdutoPreco.setForeground(new java.awt.Color(255, 255, 255));
        lblUltimoProdutoPreco.setText("Preço:");

        lblUltimoProdutoQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        lblUltimoProdutoQuantidade.setText("Quantidade:");

        lblProduto.setText("---");

        lblMarca.setText("---");

        lblPreco.setText("---");

        lblQuantidade.setText("---");

        javax.swing.GroupLayout pnlUltimoProdutoLayout = new javax.swing.GroupLayout(pnlUltimoProduto);
        pnlUltimoProduto.setLayout(pnlUltimoProdutoLayout);
        pnlUltimoProdutoLayout.setHorizontalGroup(
            pnlUltimoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUltimoProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUltimoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUltimoProduto)
                    .addGroup(pnlUltimoProdutoLayout.createSequentialGroup()
                        .addComponent(lblUltimoProdutoNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProduto))
                    .addGroup(pnlUltimoProdutoLayout.createSequentialGroup()
                        .addComponent(lblUltimoProdutoMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMarca))
                    .addGroup(pnlUltimoProdutoLayout.createSequentialGroup()
                        .addComponent(lblUltimoProdutoPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPreco))
                    .addGroup(pnlUltimoProdutoLayout.createSequentialGroup()
                        .addComponent(lblUltimoProdutoQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidade)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUltimoProdutoLayout.setVerticalGroup(
            pnlUltimoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUltimoProdutoLayout.createSequentialGroup()
                .addComponent(lblUltimoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUltimoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUltimoProdutoNome)
                    .addComponent(lblProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUltimoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUltimoProdutoMarca)
                    .addComponent(lblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUltimoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUltimoProdutoPreco)
                    .addComponent(lblPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUltimoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUltimoProdutoQuantidade)
                    .addComponent(lblQuantidade))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        btnAdd.setBackground(new java.awt.Color(102, 102, 102));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtData.setToolTipText("Formato aaaa-mm-dd");

        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setText("Data de compra:");

        javax.swing.GroupLayout pnlAdicionarProdutoLayout = new javax.swing.GroupLayout(pnlAdicionarProduto);
        pnlAdicionarProduto.setLayout(pnlAdicionarProdutoLayout);
        pnlAdicionarProdutoLayout.setHorizontalGroup(
            pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicionarProdutoLayout.createSequentialGroup()
                .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAdicionarProdutoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdicionarProdutoTitulo)
                            .addGroup(pnlAdicionarProdutoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlAdicionarProdutoLayout.createSequentialGroup()
                                        .addComponent(lblQuant)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlAdicionarProdutoLayout.createSequentialGroup()
                                        .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPrecoProd)
                                            .addComponent(lblNomeProduto)
                                            .addComponent(lblNomeMarca)
                                            .addComponent(lblData))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                            .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                            .addComponent(txtMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                            .addComponent(txtData))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlUltimoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlAdicionarProdutoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnConcluirAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlAdicionarProdutoLayout.setVerticalGroup(
            pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdicionarProdutoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAdicionarProdutoTitulo)
                .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdicionarProdutoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlUltimoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdicionarProdutoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblData))
                        .addGap(16, 16, 16)
                        .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeProduto)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeMarca)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecoProd)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuant)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar)
                    .addGroup(pnlAdicionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConcluirAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdicionarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdicionarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConcluirAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirAddActionPerformed
        JOptionPane.showMessageDialog(null, "Compra finalizada com sucesso!");
        dispose();
    }//GEN-LAST:event_btnConcluirAddActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       Produtos produto = new Produtos();
       ProdutosDAO dao = new ProdutosDAO();
       boolean status;
       int resposta;
       
       produto.setNomeProduto(txtProduto.getText());
       produto.setMarca(txtMarca.getText());
       produto.setPreco(parseFloat(txtPreco.getText()));
       produto.setQuantidade(parseInt(txtQuantidade.getText()));
       produto.setDataCompra(txtData.getText());
              
       dao = new ProdutosDAO();
       
       status = dao.conectar();
       if(status == false){
                JOptionPane.showMessageDialog(null,"Erro de conexão!");
            }else{
                resposta = dao.cadastrar(produto);
                if(resposta == 1){
                    JOptionPane.showMessageDialog(null,"Dados incluídos com sucesso!");
                                                            
                    lblProduto.setText(txtProduto.getText());
                    lblMarca.setText(txtMarca.getText());
                    lblPreco.setText(txtPreco.getText());
                    lblQuantidade.setText(txtQuantidade.getText());
                    
                    txtProduto.setText("");
                    txtMarca.setText("");
                    txtPreco.setText("");
                    txtQuantidade.setText("");
                            
                    txtProduto.requestFocus();
                    
                }else if (resposta == 1062){
                    JOptionPane.showMessageDialog(null,"Compra já foi cadastrado!");   
                }else{
                    JOptionPane.showMessageDialog(null,"Erro ao tentar inserir dados!");
                }
                dao.desconectar();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnConcluirAdd;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblAdicionarProdutoTitulo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblNomeMarca;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblPrecoProd;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblUltimoProduto;
    private javax.swing.JLabel lblUltimoProdutoMarca;
    private javax.swing.JLabel lblUltimoProdutoNome;
    private javax.swing.JLabel lblUltimoProdutoPreco;
    private javax.swing.JLabel lblUltimoProdutoQuantidade;
    private javax.swing.JPanel pnlAdicionarProduto;
    private javax.swing.JPanel pnlUltimoProduto;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
