/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pi02;

import data.Compras;
import data.Produtos;
import data.ProdutosDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ggr12
 */
public class PesquisaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form PesquisaProdutos
     */
    public PesquisaProdutos() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPesquisaProdutos = new javax.swing.JPanel();
        btnDeletar = new javax.swing.JButton();
        tblPesquisaProdutos = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        lblPesquisaProdutoTitulo = new javax.swing.JLabel();
        lblPesquisaCampo = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPesquisaProdutos.setBackground(new java.awt.Color(51, 51, 51));

        btnDeletar.setBackground(new java.awt.Color(102, 0, 0));
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("Deletar produto selecionado");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        tblProdutos.setBackground(new java.awt.Color(102, 102, 102));
        tblProdutos.setForeground(new java.awt.Color(0, 0, 0));
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome do produto", "Marca", "Preço", "Quantidade", "Data da Compra"
            }
        ));
        tblPesquisaProdutos.setViewportView(tblProdutos);

        lblPesquisaProdutoTitulo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblPesquisaProdutoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisaProdutoTitulo.setText("Pesquisa de produtos");

        lblPesquisaCampo.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisaCampo.setText("Digite o nome do produto:");

        txtPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        txtPesquisa.setForeground(new java.awt.Color(0, 0, 0));
        txtPesquisa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaCaretUpdate(evt);
            }
        });
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(102, 102, 102));
        btnVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPesquisaProdutosLayout = new javax.swing.GroupLayout(pnlPesquisaProdutos);
        pnlPesquisaProdutos.setLayout(pnlPesquisaProdutosLayout);
        pnlPesquisaProdutosLayout.setHorizontalGroup(
            pnlPesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPesquisaProdutosLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(pnlPesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPesquisaProdutosLayout.createSequentialGroup()
                        .addComponent(lblPesquisaCampo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPesquisaProdutoTitulo)
                    .addGroup(pnlPesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tblPesquisaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlPesquisaProdutosLayout.createSequentialGroup()
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletar))))
                .addGap(28, 28, 28))
        );
        pnlPesquisaProdutosLayout.setVerticalGroup(
            pnlPesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisaProdutosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblPesquisaProdutoTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisaCampo))
                .addGap(18, 18, 18)
                .addComponent(tblPesquisaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPesquisaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPesquisaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPesquisaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void preencherTabela(){
       
       ProdutosDAO produtosDAO = new ProdutosDAO();
       
       produtosDAO.conectar();
                
            String consulta = txtPesquisa.getText();
            
            if(consulta != null){
            
            List<Produtos> listaProdutos = produtosDAO.consultar(consulta);

            DefaultTableModel tabelaProdutos = (DefaultTableModel) tblProdutos.getModel();
            tabelaProdutos.setNumRows(0);

            tblProdutos.setRowSorter(new TableRowSorter(tabelaProdutos));
                      
            for (Produtos c : listaProdutos) { 
                Object[] obj = new Object[] { 
                    c.getId(),            
                    c.getNomeProduto(),   
                    c.getMarca(),
                    c.getPreco(),
                    c.getQuantidade(),
                    c.getDataCompra(),
                };
                
                tabelaProdutos.addRow(obj);
                
            }
        }    
            produtosDAO.desconectar();
   }
    
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaCaretUpdate
        preencherTabela();
    }//GEN-LAST:event_txtPesquisaCaretUpdate

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        
        ProdutosDAO dao;
        boolean status;
        int resposta;
        Produtos produto = new Produtos();
               
        produto.setId((int)tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 0));
                       
        dao = new ProdutosDAO();
        status = dao.conectar();
        
        if(status == false){
            JOptionPane.showMessageDialog(null,"Erro de conexão");
        }else{
            
            resposta = dao.excluir(produto);
                                    
            if(resposta == 1){
                JOptionPane.showMessageDialog(null,"Dados excluídos com sucesso!");
                                              
            }else{
                JOptionPane.showMessageDialog(null,"Erro ao tentar excluir dados!");
            }
            
            preencherTabela();
            
            dao.desconectar();
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblPesquisaCampo;
    private javax.swing.JLabel lblPesquisaProdutoTitulo;
    private javax.swing.JPanel pnlPesquisaProdutos;
    private javax.swing.JScrollPane tblPesquisaProdutos;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
